import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import Posts from '../assets/images/Posts.png'
import styles from './styles.module.css'
import { useRouter } from 'next/router'


const Home: NextPage = () => {
  const router = useRouter()
  return (
    <div className=''>
      <Head>
        <title>mLabs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <main className={styles.mainContainer}>
        <div className={styles.postsImage}>
          <Image src={Posts} width={280} height={440} alt="Posts Image" objectFit='contain' />
        </div>
        <div>
          <button className={`${styles.agenda} btn`} onClick={() => router.push('/scheduling')}>
            Agendar post
          </button>
        </div>
      </main>

    </div>
  )
}

export default Home
